### ISSUE TITLE
Renpy problem in DDE

### ISSUE THREAD

**Issue by Dumbo-programmer** [linuxdeepin/dtkgui#16] opened 2021-12-13 14:22 UTC
when running any game(visual novel mostly) made in renpy, the whole DE window effects start to artifact
Like the task bar automatically switches to efficient mode, all windows switch to rough corners and windows effect toggle turns off when trying to turn on nothing happens

**Comment by BLumia** [comment] 2022-07-15 08:18
Sorry for the super late reply since we didn't look into issues that created outside the developer-center repo.

I'll close this one for now since it's not the correct repo for this issue. If you still have this issue on DDE, could you create a new issue at the [developer-center](https://github.com/linuxdeepin/developer-center) repo and provide a minimum project that can be used to reproduce this issue? We'll look into it once we can reproduce the issue. Thanks!

**Closed by BLumia** 2022-07-15 08:18 UTC
